# Site settings
title: Pixelite
email: email@pixelite.co.nz
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://pixelite.co.nz"
twitter_username: wiifm
github_username:  wiifm69
facebook_username:  sean.hamlin

# Build settings
markdown: kramdown
permalink: /article/:title
paginate: 5
exclude: ["node_modules"]
